language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
  - pip install --only-binary=pandas dask[dataframe] pytest
  - pip install -e .

script:
    - travis_wait py.test

notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: change
