language: python

python:
    - "2.7"
    # - "3.4"    # too slow to build pandas
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
  - pip install --only-binary=pandas pytest
  - pip install -e .

script:
    - travis_wait py.test

notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: change
